name: SIMPL SHARP ACTIONS TEST

on:
  workflow_dispatch:
          
jobs:
  simpl-sharp-build:
    
    runs-on: ubuntu-latest    

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Simpl Sharp
      uses: ewilliams0305/simpl-sharp-actions@v0.0.7
      with: 
        project: example/SimplSharp.Action.Clz
        targets: net472
        configuration: Release