name: SIMPL SHARP ACTIONS TEST

on:
  workflow_dispatch:
          
jobs:
  simpl-sharp-build:
    
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        project: ['example/SimplSharp.Action.Clz/SimplSharp.Action.Clz.csproj', 'example/SimplSharp.Targets.Cpz/SimplSharp.Targets.Cpz.csproj']
        target: ['net472']
        configuration: [Release]

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Simpl Sharp
      uses: ewilliams0305/simpl-sharp-actions@v0.1.2
      id: simplsharp 
      with: 
        project: ${{ matrix.project }}
        targets: ${{ matrix.target }}
        configuration: ${{ matrix.configuration }}

    - name: Display CLZ Output path
      run: echo ${{ steps.simplsharp.outputs.file_output }}

      # Note: The output path will be relative to your workspace hence adding the ./ to the begining
      # in this example an input: example/SimplSharp.Action.Clz/SimplSharp.Action.Clz.csproj will produce a file path clz/net472/SimplSharp.Action.Clz.clz
    - name: Upload CLZ Artifact
      uses: actions/upload-artifact@v4
      with:
        name: file_output
        path: ./${{ steps.simplsharp.outputs.file_output }}

      # Note: The we can target the aartifact directory for each and every clz file
      # in this example an input: example/SimplSharp.Action.Clz/SimplSharp.Action.Clz.csproj will produce a glob path clz/*/**.clz
    - name: Upload CLZ Artifact
      uses: actions/upload-artifact@v4
      with:
        name: file_outputs
        path: ./${{ steps.simplsharp.outputs.artifacts_path }}

    - name: Validate the CLZ path
      run: |
        if [ ! -f ./${{ steps.simplsharp.outputs.file_output }} ]; then
          echo "Error: CLZ file not found at ./${{ steps.simplsharp.outputs.file_output }}"
          exit 1
        fi